from pathlib import Path
p=Path('MAXESS-RESULTS-10-GROOVE.html')
s=p.read_text(encoding='utf-8')
marker='MAXESS_RESULTS_V19B_EXECUTION'
if marker in s: raise SystemExit('V19B already applied')
layer=r'''<!-- MAXESS_RESULTS_V19B_EXECUTION -->
<style id="maxess-results-v19b">
#maxess-results-10.v19b{display:flex!important;flex-direction:column!important;overflow-x:hidden!important}
#maxess-results-10.v19b>.v19b-naya{order:1!important}#maxess-results-10.v19b>.v19b-hero{order:2!important}#maxess-results-10.v19b>.v19b-dims{order:3!important}#maxess-results-10.v19b>.v19b-listen{order:4!important}#maxess-results-10.v19b>.v19b-pattern{order:5!important}#maxess-results-10.v19b>.v19b-meaning{order:6!important}#maxess-results-10.v19b>.v19b-strength{order:7!important}#maxess-results-10.v19b>.v19b-lever{order:8!important}#maxess-results-10.v19b>.v19b-action{order:9!important}#maxess-results-10.v19b>.v19b-video{order:10!important}#maxess-results-10.v19b>.v19b-trial{order:11!important}#maxess-results-10.v19b>.v19b-masters{order:12!important}#maxess-results-10.v19b>.v19b-playground{order:13!important}#maxess-results-10.v19b>.v19b-tech{order:14!important}
.v19b-orbs{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:12px!important}.v19b-orb{min-height:160px!important;border-radius:50%!important;display:grid!important;place-items:center!important;text-align:center!important;background:radial-gradient(circle,#2b1645,#07040b 68%)!important;border:1px solid rgba(208,168,255,.45)!important;box-shadow:inset 0 0 35px rgba(166,108,255,.2),0 12px 35px rgba(0,0,0,.3)!important}.v19b-orb b{font-size:38px!important;display:block!important;color:#fff!important}.v19b-orb span{display:block!important;font-size:9px!important;letter-spacing:.1em!important;text-transform:uppercase!important;color:rgba(255,255,255,.7)!important}.v19b-label{text-align:center!important;color:#fff!important;font-size:16px!important;font-weight:950!important;letter-spacing:.28em!important;margin-bottom:18px!important}.v19b-lever{text-align:center!important}.v19b-tech{text-align:center!important}
@media(max-width:900px){.v19b-orbs{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:520px){.v19b-orb{min-height:135px!important}.v19b-orb b{font-size:32px!important}}
</style>
<script id="maxess-results-v19b">
(function(){function go(){var r=document.getElementById('maxess-results-10');if(!r)return;var tx=function(e){return(e&&e.textContent||'').replace(/\s+/g,' ').trim().toLowerCase()},top=function(e){while(e&&e.parentElement!==r)e=e.parentElement;return e},find=function(a){var n=r.querySelectorAll('section,article,div');for(var i=0;i<n.length;i++){var x=tx(n[i]);for(var j=0;j<a.length;j++){if(x.indexOf(a[j])>-1){var b=top(n[i]);if(b)return b}}}return null},add=function(e,c){if(e){e.classList.add(c);r.appendChild(e)}};
var hero=top(r.querySelector('.mx-hero'));var dims=top(r.querySelector('.mx-dim-grid,.v13-dim-grid,.v17-dimensions,#v13-dimensions'));var naya=find(['hi, look at your results','you have seen your patterns','you\'ve seen your patterns']);var pat=find(['your pattern']);var mea=find(['what it means','meaning']);var str=find(['your strength']);var lev=find(['biggest lever']);var act=find(['your move']);var vid=find(['watch the video']);var tri=find(['free trial']);var mas=find(['18 naya masters','18 masters']);var ply=find(['learn what ai can do for you','don\'t learn ai']);var tech=find(['technology should amplify the human']);
if(!naya){naya=document.createElement('section');naya.innerHTML='<div style="padding:26px 20px;text-align:center"><b>NAYA</b><h1>Hi. Look at your results.</h1><p>This is not a judgment. It is a map — with Naya.</p></div>';r.insertBefore(naya,r.firstChild)}
add(naya,'v19b-naya');add(hero,'v19b-hero');add(dims,'v19b-dims');
if(dims){var g=dims.querySelector('.mx-dim-grid,.v13-dim-grid,.v17-dim-grid');if(g){g.classList.add('v19b-orbs');var d=(window.MAXESS_RESULT&&window.MAXESS_RESULT.dimensions)||[],names=['Direction','Communication','Evaluation','Iteration','Systems Thinking'];for(var i=0;i<5;i++){var c=g.children[i]||document.createElement('div');c.className='v19b-orb';c.innerHTML='<div><b>'+((d[i]&&d[i].score)||'')+'</b><span>'+((d[i]&&d[i].name)||names[i])+'</span></div>';g.appendChild(c)}while(g.children.length>5)g.removeChild(g.lastChild)}}
if(hero){var l=document.createElement('div');l.className='v19b-label';l.textContent='YOUR AI SCORE';hero.insertBefore(l,hero.firstChild);var s=hero.querySelector('.mx-score strong');if(s)s.textContent=(window.MAXESS_RESULT&&window.MAXESS_RESULT.overallScore)||'';var all=hero.querySelectorAll('.mx-score strong');for(var q=1;q<all.length;q++)all[q].textContent=''}
var listen=find(['listen to naya']);if(listen&&listen!==hero)add(listen,'v19b-listen');add(pat,'v19b-pattern');add(mea,'v19b-meaning');add(str,'v19b-strength');add(lev,'v19b-lever');add(act,'v19b-action');add(vid,'v19b-video');add(tri,'v19b-trial');add(mas,'v19b-masters');add(ply,'v19b-playground');add(tech,'v19b-tech');if(tech)r.appendChild(tech);r.classList.add('v19b');r.setAttribute('data-maxess-v19-order','NAYA|ORB|MINI_ORBS|LISTEN|PATTERN|MEANING|STRENGTH|LEVER|ACTION|VIDEO|TRIAL|MASTERS|PLAYGROUND|TECH')}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',go);else go()})();
</script>
'''
i=s.lower().rfind('</body>')
if i<0: raise SystemExit('No </body> in actual Groove file')
p.write_text(s[:i]+layer+s[i:],encoding='utf-8')
print('V19B written to actual Groove artifact')
